export enum FileMimeTypesEnum {
  PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  BMP = 'image/bmp',
  CSV = 'text/csv',
  DOC = 'application/msword',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  JPEG = 'image/jpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  JPG = 'image/jpeg',
  ODP = 'application/vnd.oasis.opendocument.presentation',
  ODS = 'application/vnd.oasis.opendocument.spreadsheet',
  ODT = 'application/vnd.oasis.opendocument.text',
  PNG = 'image/png',
  PDF = 'application/pdf',
  PPT = 'application/vnd.ms-powerpoint',
  SVG = 'image/svg+xml',
  TIF = 'image/tiff',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  TIFF = 'image/tiff',
  TXT = 'text/plain',
  VSD = 'application/vnd.visio',
  WEBP = 'image/webp',
  XLS = 'application/vnd.ms-excel',
  XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  JSON = 'application/json',
  BINARY = 'application/octet-stream',
}
